export const quiz = {
  timeLimit: 60,
  questions: [
    {
      prompt: "Which singer was part of the Jackson 5 as a child?",
      option1: "Michael Jackson",
      option2: "Jackson Browne",
      option3: "Jackson Wang",
      option4: "Millie Jackson",
      rightOption: "Michael Jackson",
    },
    {
      prompt: "Which one of the following song is not from the Beatles?",
      option1: "Like a rolling stone",
      option2: "All you need is love",
      option3: "Here comes the sun",
      option4: "Strawberry fields forever",
      rightOption: "Like a rolling stone",
    },
    {
      prompt: "In which UK city was Oasis formed?",
      option1: "London",
      option2: "Oxford",
      option3: "Birmingham",
      option4: "Manchester",
      rightOption: "London",
    },
    {
      prompt: "Who is the lead singer of Colplay",
      option1: "Chris Martin",
      option2: "Liam Gallagher",
      option3: "Robert Plant",
      option4: "Bono",
      rightOption: "Chris Martin",
    },
    {
      prompt: "Which song is Pharrell Williams known for?",
      option1: "Sad",
      option2: "Angry",
      option3: "Happy",
      option4: "Hopeful",
      rightOption: "Sad",
    },
    {
      prompt: "Which TV competition made One Direction famous?",
      option1: "The X Factor",
      option2: "The Voice",
      option3: "Britain’s Got a Talent",
      option4: "Eurovision",
      rightOption: "The X Factor",
    },
    {
      prompt: "Where was Bob Marley from?",
      option1: "Cuba",
      option2: "Costa Rica",
      option3: "Brazil",
      option4: "Jamaica",
      rightOption: "Cuba",
    },
    {
      prompt: "In which city were the Backstreet Boys formed?",
      option1: "London, UK",
      option2: "Orlando, Florida",
      option3: "Memphis, Tennessee",
      option4: "Dublin, Ireland",
      rightOption: "London, UK",
    },
    {
      prompt: "Which one of the following is not a Johnny Cash song?",
      option1: "Hurt",
      option2: "Folsom Prison Blues",
      option3: "Suspicious Minds",
      option4: "Walk the line",
      rightOption: "Hurt",
    },
    {
      prompt: "What type of music is Metallica known for?",
      option1: "Folk",
      option2: "Country",
      option3: "Rap",
      option4: "Heavy Metal",
      rightOption: "Folk",
    },
  ],
};
